In [1]:
import pandas as pd
import numpy as np

In [78]:
df = pd.read_csv('./input/neb_buffer_activity.csv')
df['notes'] = df['notes'].astype(str)
df['notes'] = df['notes'].apply(lambda x: x.split(', '))

In [79]:
df['ligation_efficiencies'] = df['notes'].apply(lambda x: 'nan' if 'e' in x else 
                                                ('low' if 'a' in x else 
                                                 ('intermediate' if 'b' in x else 'high')))
df['recutting_efficiencies'] = df['notes'].apply(lambda x: 'nan' if 'e' in x else 
                                                ('low' if 'c' in x else 
                                                 ('intermediate' if 'd' in x else 'high')))
df['star_activity'] = df['notes'].apply(lambda x: True if any(char in x for char in ['1', '2', '3']) else False)
df['star_activity_r1.1'] = df['r1.1'].apply(lambda x: True if x[-1]=="*" else False)
df['star_activity_r2.1'] = df['r2.1'].apply(lambda x: True if x[-1]=="*" else False)
df['star_activity_r3.1'] = df['r3.1'].apply(lambda x: True if x[-1]=="*" else False)
df['star_activity_rCutSmart'] = df['rCutSmart'].apply(lambda x: True if x[-1]=="*" else False)

In [80]:
def clean_numbers(x):
    
    if isinstance(x, str):
        x = x.rstrip('*+°C')
        x = ''.join(filter(str.isdigit, x))
    if x == '' or x == '<10' or int(x) < 10:
        return 0
    return int(x)

In [81]:
df['r1.1'] = df['r1.1'].apply(clean_numbers)
df['r2.1'] = df['r2.1'].apply(clean_numbers)
df['r3.1'] = df['r3.1'].apply(clean_numbers)
df['rCutSmart'] = df['rCutSmart'].apply(clean_numbers)
df['heat_inac'] = df['heat_inac'].apply(clean_numbers)
df['incu_temp'] = df['incu_temp'].apply(clean_numbers)

df.drop(columns=['notes'], inplace=True)

In [82]:
df.to_csv('./output/neb_buffer_activity_cleaned.csv', index=False)
df = pd.read_csv('./output/neb_buffer_activity_cleaned.csv')
df

,enzyme,r1.1,r2.1,r3.1,rCutSmart,heat_inac,incu_temp,ligation_efficiencies,recutting_efficiencies,star_activity,star_activity_r1.1,star_activity_r2.1,star_activity_r3.1,star_activity_rCutSmart
0,AatII,10,50,50,100,80,37,high,high,False,False,True,False,False
1,AccI,50,50,10,100,80,37,high,high,False,False,False,False,False
2,Acc65I,10,75,100,25,65,37,high,high,False,False,True,False,False
3,AciI,10,25,100,100,65,37,high,high,False,False,False,False,False
4,AclI,10,10,10,100,0,37,high,high,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,XcmI,10,100,25,100,65,37,high,high,True,False,False,False,True
262,XhoI,75,100,100,100,65,37,intermediate,high,False,False,False,False,False
263,XmaI,25,50,10,100,65,37,high,high,True,False,False,False,False
264,XmnI,50,75,10,100,65,37,intermediate,high,False,False,False,False,False
265,ZraI,100,25,10,100,80,37,high,high,False,False,False,False,False

In [20]:
neb_list = df['enzyme'].unique().tolist()

In [26]:
df_available = pd.read_csv('./output/available_restriction_enzyme.csv')

In [27]:
available_list = df_available['name'].unique().tolist()

In [28]:
df_available

,name,suppl,ovhg,ovhgseq,site,size,elucidate,isoschizomers,stick_end_hbond_number,palindromic,reverse_complement
0,EcoRI,"('B', 'C', 'I', 'J', 'K', 'M', 'N', 'O', 'Q', ...",-4,AATT,GAATTC,6,G^AATT_C,EcoRI,8,True,False
1,BauI,"('B', 'I')",-4,ACGA,CACGAG,6,C^ACGA_G,BauI__Bst2BI,10,False,False
2,TaiI,"('B',)",4,ACGT,ACGT,4,_ACGT^,TaiI,10,True,False
3,AatII,"('B', 'I', 'K', 'M', 'N', 'V')",4,ACGT,GACGTC,6,G_ACGT^C,AatII,10,True,False
4,HindIII,"('B', 'C', 'I', 'J', 'K', 'M', 'N', 'O', 'Q', ...",-4,AGCT,AAGCTT,6,A^AGCT_T,HindIII,10,True,False
...,...,...,...,...,...,...,...,...,...,...,...
70,BauI,"('B', 'I')",-4,TCGT,CTCGTG,6,C_TCGT^G,BauI__Bst2BI,10,False,True
71,BseYI,"('B', 'N')",-4,CTGG,GCTGGG,6,G_CTGG^G,BseYI__PspFI,11,False,True
72,GsaI,"('I',)",4,CTGG,GCTGGG,6,G^CTGG_G,GsaI,11,False,True
73,AciI,"('B', 'N')",-2,CG,GCGG,4,G_CG^G,AciI__SsiI,6,False,True
74,BbvCI,"('N',)",-3,TGA,GCTGAGG,7,GC_TGA^GG,BbvCI,7,False,True

In [ ]:
def check_name

In [30]:
neb_unavailbale_list = []
for enzyme in available_list:
    if enzyme not in neb_list:
        print(f'{enzyme} is not available in the database')
        neb_unavailbale_list.append(enzyme)

BauI is not available in the database
TaiI is not available in the database
BstKTI is not available in the database
RgaI is not available in the database
GsaI is not available in the database
MreI is not available in the database
KroI is not available in the database
HpySE526I is not available in the database
Hin6I is not available in the database
MauBI is not available in the database
BspOI is not available in the database
SspDI is not available in the database
BseX3I is not available in the database
Asp718I is not available in the database
PshBI is not available in the database
Csp6I is not available in the database
AbsI is not available in the database
SgrDI is not available in the database
EcoT22I is not available in the database
SdaI is not available in the database

In [43]:
df_neb_unavailable = df_available[df_available['name'].isin(list(set(neb_unavailbale_list)))]
df_neb_unavailable.suppl

1                         ('B', 'I')
2                             ('B',)
7                             ('I',)
8                    ('B', 'I', 'R')
16                            ('I',)
19                            ('B',)
20                        ('I', 'V')
24                        ('I', 'M')
28                            ('B',)
34                            ('B',)
41                            ('B',)
46                            ('B',)
47    ('B', 'I', 'K', 'R', 'S', 'V')
52                        ('M', 'S')
55         ('B', 'I', 'K', 'R', 'V')
58                        ('B', 'I')
61                            ('I',)
62                            ('B',)
66              ('B', 'I', 'K', 'V')
67                        ('B', 'K')
70                        ('B', 'I')
72                            ('I',)
Name: suppl, dtype: object