In [1]:
import Bio

In [17]:
import pandas as pd
from Bio.Restriction import AllEnzymes

AllEnzymes

RestrictionBatch(['AanI', 'AarI', 'AasI', 'AatII', 'Aba6411II', 'AbaB8342IV', 'AbaCIII', 'AbaSI', 'AbaUMB2I', 'AbsI', 'Acc16I', 'Acc36I', 'Acc65I', 'Acc65V', 'AccB1I', 'AccB7I', 'AccBSI', 'AccI', 'AccII', 'AccIII', 'AceIII', 'AchA6III', 'AciI', 'AclI', 'AclWI', 'Aco12261II', 'AcoI', 'AcoY31II', 'AcsI', 'AcuI', 'AcvI', 'AcyI', 'AdeI', 'Adh6U21I', 'AfaI', 'AfeI', 'AfiI', 'AflII', 'AflIII', 'AgeI', 'AgsI', 'AhaIII', 'AhdI', 'AhlI', 'AhyRBAHI', 'AhyYL17I', 'AjiI', 'AjnI', 'AjuI', 'AleI', 'AlfI', 'AloI', 'AluBI', 'AluI', 'Alw21I', 'Alw26I', 'Alw44I', 'AlwFI', 'AlwI', 'AlwNI', 'Ama87I', 'AmaCSI', 'Aod1I', 'Aor13HI', 'Aor51HI', 'AoxI', 'ApaBI', 'ApaI', 'ApaLI', 'ApeKI', 'ApoI', 'ApyPI', 'AquII', 'AquIII', 'AquIV', 'ArsI', 'AscI', 'AseI', 'Asi256I', 'AsiGI', 'AsiSI', 'Asp103I', 'Asp114pII', 'Asp700I', 'Asp718I', 'AspA2I', 'AspBHI', 'AspDUT2V', 'AspJHL3II', 'AspLEI', 'AspNIH4III', 'AspS9I', 'AspSLV7III', 'Asu14238IV', 'AsuC2I', 'AsuHPI', 'AsuI', 'AsuII', 'AsuNHI', 'AteTI', 'AvaI', 'AvaII', 'AvaIII', 'AvrII', 'Awo1030IV', 'AxyI', 'BaeGI', 'BaeI', 'Bag18758I', 'BalI', 'BamHI', 'BanI', 'BanII', 'BanLI', 'BarI', 'Bau1417V', 'BauI', 'Bbr52II', 'Bbr57III', 'Bbr7017II', 'Bbr7017III', 'BbrPI', 'BbsI', 'BbuB31I', 'BbuB31II', 'Bbv12I', 'BbvCI', 'BbvI', 'BbvII', 'BccI', 'Bce3081I', 'Bce83I', 'BceAI', 'BceSIV', 'BcefI', 'BcgI', 'BciT130I', 'BciVI', 'BclI', 'BcnI', 'BcoDI', 'BcuI', 'BdaI', 'BetI', 'BfaI', 'BfaSII', 'BfiI', 'BfmI', 'BfoI', 'BfrI', 'BfuAI', 'BfuI', 'Bga514I', 'BglI', 'BglII', 'BinI', 'BisI', 'BkrAM31DI', 'Ble402II', 'BlnI', 'BloAII', 'BlpI', 'BlsI', 'BmcAI', 'Bme1390I', 'Bme18I', 'BmeDI', 'BmeRI', 'BmeT110I', 'BmgBI', 'BmgI', 'BmgT120I', 'BmiI', 'BmrFI', 'BmrI', 'BmsI', 'BmtI', 'BmuI', 'BoxI', 'BpiI', 'BplI', 'BpmI', 'Bpu10I', 'Bpu1102I', 'Bpu14I', 'BpuEI', 'BpuMI', 'Bsa29I', 'BsaAI', 'BsaBI', 'BsaHI', 'BsaI', 'BsaJI', 'BsaWI', 'BsaXI', 'BsbI', 'Bsc4I', 'BscAI', 'BscGI', 'Bse118I', 'Bse1I', 'Bse21I', 'Bse3DI', 'Bse8I', 'BseAI', 'BseBI', 'BseCI', 'BseDI', 'BseGI', 'BseJI', 'BseLI', 'BseMI', 'BseMII', 'BseNI', 'BsePI', 'BseRI', 'BseSI', 'BseX3I', 'BseXI', 'BseYI', 'BsgI', 'Bsh1236I', 'Bsh1285I', 'BshFI', 'BshNI', 'BshTI', 'BshVI', 'BsiEI', 'BsiHKAI', 'BsiHKCI', 'BsiI', 'BsiSI', 'BsiWI', 'BsiYI', 'BslFI', 'BslI', 'BsmAI', 'BsmBI', 'BsmFI', 'BsmI', 'BsnI', 'Bso31I', 'BsoBI', 'Bsp119I', 'Bsp120I', 'Bsp1286I', 'Bsp13I', 'Bsp1407I', 'Bsp143I', 'Bsp1720I', 'Bsp19I', 'Bsp24I', 'Bsp3004IV', 'Bsp460III', 'Bsp68I', 'BspACI', 'BspANI', 'BspCNI', 'BspD6I', 'BspDI', 'BspEI', 'BspFNI', 'BspGI', 'BspHI', 'BspLI', 'BspLU11I', 'BspMAI', 'BspMI', 'BspMII', 'BspNCI', 'BspOI', 'BspPI', 'BspQI', 'BspT104I', 'BspT107I', 'BspTI', 'BspTNI', 'BsrBI', 'BsrDI', 'BsrFI', 'BsrGI', 'BsrI', 'BssAI', 'BssECI', 'BssHII', 'BssMI', 'BssNAI', 'BssNI', 'BssSI', 'BssT1I', 'Bst1107I', 'Bst2BI', 'Bst2UI', 'Bst4CI', 'Bst6I', 'BstACI', 'BstAFI', 'BstAPI', 'BstAUI', 'BstBAI', 'BstBI', 'BstC8I', 'BstDEI', 'BstDSI', 'BstEII', 'BstENI', 'BstF5I', 'BstFNI', 'BstH2I', 'BstHHI', 'BstKTI', 'BstMAI', 'BstMBI', 'BstMCI', 'BstMWI', 'BstNI', 'BstNSI', 'BstPAI', 'BstPI', 'BstSCI', 'BstSFI', 'BstSLI', 'BstSNI', 'BstUI', 'BstV1I', 'BstV2I', 'BstX2I', 'BstXI', 'BstYI', 'BstZ17I', 'BstZI', 'Bsu15I', 'Bsu36I', 'BsuI', 'BsuRI', 'BsuTUI', 'BtgI', 'BtgZI', 'BthCI', 'BtrI', 'BtsCI', 'BtsI', 'BtsIMutI', 'BtuMI', 'Bve1B23I', 'BveI', 'Cac8I', 'CaiI', 'Cal14237I', 'CalB3II', 'Cau10061II', 'CauII', 'Cba13II', 'Cba16038I', 'Cbo67071IV', 'Cch467III', 'CchII', 'CchIII', 'CciI', 'CciNI', 'Cco14983V', 'Cco14983VI', 'CcrNAIII', 'Cdi11397I', 'CdiI', 'CdpI', 'Cdu23823II', 'CfoI', 'Cfr10I', 'Cfr13I', 'Cfr42I', 'Cfr9I', 'CfrI', 'CfrMH13II', 'CfrMH16VI', 'Cfupf3II', 'Cgl13032I', 'Cgl13032II', 'ChaI', 'Cje265V', 'Cje54107III', 'CjeFIII', 'CjeFV', 'CjeI', 'CjeNII', 'CjeNIII', 'CjeNV', 'CjeP659IV', 'CjePI', 'CjuI', 'CjuII', 'Cla11845III', 'ClaI', 'Cly7489II', 'Cma23826I', 'CpoI', 'CseI', 'CsiI', 'Csp2014I', 'Csp6I', 'CspAI', 'CspCI', 'CspI', 'CstMI', 'CviAII', 'CviJI', 'CviKI_1', 'CviQI', 'CviRI', 'Dde51507I', 'DdeI', 'DinI', 'DpnI', 'DpnII', 'DraI', 'DraII', 'DraIII', 'DraRI', 'DrdI', 'DrdII', 'DrdIV', 'DriI', 'DsaI', 'DseDI', 'DvuIII', 'EaeI', 'EagI', 'Eam1104I', 'Eam1105I', 'EarI', 'EciI', 'Ecl136II', 'Ecl234I', 'Ecl35734I', 'EclXI', 'Eco105I', 'Eco130I', 'Eco147I', 'Eco24I', 'Eco31I', 'Eco32I', 'Eco43896II', 'Eco4465II', 'Eco47I', 'Eco47III', 'Eco52I', 'Eco53kI', 'Eco57I', 'Eco57MI', 'Eco72I', 'Eco81I', 'Eco88I', 'Eco91I', 'EcoBLMcrX', 'EcoE1140I', 'EcoHI', 'EcoHSI', 'EcoICRI', 'EcoMVII', 'EcoNI', 'EcoNIH6II', 'EcoO109I', 'EcoO65I', 'EcoRI', 'EcoRII', 'EcoRV', 'EcoT14I', 'EcoT22I', 'EcoT38I', 'EgeI', 'EheI', 'Eli8509II', 'ErhI', 'EsaBC3I', 'EsaSSI', 'Esp3007I', 'Esp3I', 'EspI', 'FaeI', 'FaiI', 'FalI', 'FaqI', 'FatI', 'FauI', 'FauNDI', 'FbaI', 'FblI', 'Fco1691IV', 'FinI', 'FmuI', 'Fnu4HI', 'FnuDII', 'FokI', 'FriOI', 'FseI', 'Fsp4HI', 'FspAI', 'FspBI', 'FspEI', 'FspI', 'FspPK15I', 'FtnUV', 'GauT27I', 'Gba708II', 'GdiII', 'GlaI', 'GluI', 'GsaI', 'GsuI', 'HaeI', 'HaeII', 'HaeIII', 'HapII', 'HauII', 'HbaII', 'HdeNY26I', 'HdeZA17I', 'HgaI', 'HgiAI', 'HgiCI', 'HgiEII', 'HgiJII', 'HhaI', 'Hin1I', 'Hin1II', 'Hin4I', 'Hin4II', 'Hin6I', 'HinP1I', 'HincII', 'HindII', 'HindIII', 'HinfI', 'HpaI', 'HpaII', 'HphI', 'Hpy166II', 'Hpy178III', 'Hpy188I', 'Hpy188III', 'Hpy300XI', 'Hpy8I', 'Hpy99I', 'Hpy99XIII', 'Hpy99XIV', 'Hpy99XIV_mut1', 'Hpy99XXII', 'HpyAV', 'HpyAXIV', 'HpyAXVIII', 'HpyAXVI_mut1', 'HpyAXVI_mut2', 'HpyCH4III', 'HpyCH4IV', 'HpyCH4V', 'HpyF10VI', 'HpyF3I', 'HpySE526I', 'HpyUM032XIII', 'HpyUM032XIII_mut1', 'HpyUM032XIV', 'HpyUM037X', 'Hsp92I', 'Hsp92II', 'HspAI', 'HspMHR1II', 'Jma19592I', 'Jma19592II', 'Jsp2502II', 'KasI', 'KflI', 'Kor51II', 'Kpn156V', 'Kpn2I', 'Kpn327I', 'KpnI', 'KpnNH25III', 'KpnNIH30III', 'KpnNIH50I', 'KroI', 'Ksp22I', 'Ksp632I', 'KspAI', 'KspI', 'Kzo9I', 'Lba2029III', 'Lde4408II', 'LguI', 'LlaG50I', 'LmnI', 'Lmo370I', 'Lmo911II', 'Lpl1004II', 'LpnI', 'LpnPI', 'Lra68I', 'LsaDS4I', 'Lsp1109I', 'Lsp48III', 'Lsp6406VI', 'LweI', 'MabI', 'MaeI', 'MaeII', 'MaeIII', 'MalI', 'MaqI', 'MauBI', 'Mba11I', 'MbiI', 'MboI', 'MboII', 'McaTI', 'Mcr10I', 'McrI', 'MfeI', 'MflI', 'MhlI', 'MjaIV', 'MkaDII', 'MlsI', 'Mlu211III', 'MluCI', 'MluI', 'MluNI', 'Mly113I', 'MlyI', 'MmeI', 'MnlI', 'Mox20I', 'Mph1103I', 'MreI', 'MroI', 'MroNI', 'MroXI', 'MscI', 'MseI', 'MslI', 'Msp20I', 'MspA1I', 'MspCI', 'MspGI', 'MspI', 'MspI7II', 'MspI7IV', 'MspJI', 'MspR9I', 'MspSC27II', 'MssI', 'MstI', 'MteI', 'MtuHN878II', 'MunI', 'Mva1269I', 'MvaI', 'MvnI', 'MwoI', 'NaeI', 'Nal45188II', 'NarI', 'Nbr128II', 'NciI', 'NcoI', 'NdeI', 'NdeII', 'NgoAVII', 'NgoAVIII', 'NgoMIV', 'NhaXI', 'NheI', 'NhoI', 'NlaCI', 'NlaIII', 'NlaIV', 'Nli3877I', 'NmeA6CIII', 'NmeAIII', 'NmeDI', 'NmuCI', 'NotI', 'NpeUS61II', 'NruI', 'NsbI', 'NsiI', 'NspBII', 'NspI', 'NspV', 'ObaBS10I', 'OgrI', 'OliI', 'OspHL35III', 'PabI', 'Pac19842II', 'PacI', 'PacIII', 'PaeI', 'PaeR7I', 'PagI', 'Pal408I', 'PalAI', 'PasI', 'PauI', 'Pba2294I', 'PcaII', 'PceI', 'PciI', 'PciSI', 'Pcr308II', 'PcsI', 'PctI', 'Pdi8503III', 'PdiI', 'PdmI', 'Pdu1735I', 'PenI', 'PfeI', 'Pfl1108I', 'Pfl23II', 'Pfl8569I', 'PflFI', 'PflMI', 'PflPt14I', 'PfoI', 'PfrJS12IV', 'PfrJS12V', 'PfrJS15III', 'Pin17FIII', 'PinAI', 'PinP23II', 'PinP59III', 'PkrI', 'PlaDI', 'Ple19I', 'PleI', 'PliMI', 'PluTI', 'PmaCI', 'PmeI', 'PmlI', 'PpiI', 'PpiP13II', 'PpsI', 'Ppu10I', 'Ppu21I', 'PpuMI', 'PscI', 'Pse18267I', 'PshAI', 'PshBI', 'PsiI', 'Psp0357II', 'Psp03I', 'Psp124BI', 'Psp1406I', 'Psp5II', 'Psp6I', 'PspCI', 'PspEI', 'PspFI', 'PspGI', 'PspLI', 'PspN4I', 'PspOMI', 'PspOMII', 'PspPI', 'PspPPI', 'PspPRI', 'PspXI', 'PsrI', 'PssI', 'Pst14472I', 'Pst145I', 'Pst273I', 'PstI', 'PstNI', 'PsuGI', 'PsuI', 'PsyI', 'PteI', 'PvuI', 'PvuII', 'Rba2021I', 'RceI', 'RdeGBI', 'RdeGBII', 'RdeGBIII', 'RflFIII', 'RgaI', 'RigI', 'RlaI', 'RlaII', 'RleAI', 'Rmu369III', 'RpaB5I', 'RpaBI', 'RpaI', 'RpaTI', 'RruI', 'RsaI', 'RsaNI', 'RseI', 'Rsp008IV', 'Rsp008V', 'Rsp531II', 'RspPBTS2III', 'Rsr2I', 'RsrII', 'Rtr1953I', 'SacI', 'SacII', 'Saf8902III', 'Sag901I', 'SalI', 'SanDI', 'SapI', 'SaqAI', 'SatI', 'Sau3AI', 'Sau96I', 'SauI', 'Sba460II', 'SbfI', 'Sbo46I', 'ScaI', 'SchI', 'SciI', 'ScoDS2II', 'ScrFI', 'SdaI', 'SdeAI', 'SdeOSI', 'SduI', 'SecI', 'SelI', 'Sen17963III', 'SenA1673III', 'SenSARA26III', 'SenTFIV', 'SetI', 'SexAI', 'SfaAI', 'SfaNI', 'SfcI', 'SfeI', 'SfiI', 'SfoI', 'Sfr274I', 'Sfr303I', 'SfuI', 'SgeI', 'SgfI', 'SgrAI', 'SgrBI', 'SgrDI', 'SgrTI', 'SgsI', 'SimI', 'SinI', 'SlaI', 'SmaI', 'SmaUMH5I', 'SmaUMH8I', 'SmiI', 'SmiMI', 'SmlI', 'SmoI', 'SnaBI', 'SnaI', 'Sno506I', 'SpeI', 'SphI', 'SplI', 'SpnRII', 'SpoDI', 'SrfI', 'Sse232I', 'Sse8387I', 'Sse8647I', 'Sse9I', 'SseBI', 'SsiI', 'Ssp6803IV', 'Ssp714II', 'SspD5I', 'SspDI', 'SspI', 'SspMI', 'SstE37I', 'SstI', 'Sth132I', 'Sth20745III', 'Sth302II', 'SthSt3II', 'StsI', 'StuI', 'StyD4I', 'StyI', 'SurP32aII', 'SwaI', 'TaaI', 'TaiI', 'TaqI', 'TaqII', 'TaqIII', 'TasI', 'TatI', 'TauI', 'TfiI', 'TpyTP2I', 'Tru1I', 'Tru9I', 'TscAI', 'TseFI', 'TseI', 'TsoI', 'Tsp45I', 'Tsp4CI', 'TspARh3I', 'TspDTI', 'TspEI', 'TspGWI', 'TspMI', 'TspRI', 'TssI', 'TstI', 'TsuI', 'Tth111I', 'Tth111II', 'UbaF11I', 'UbaF12I', 'UbaF13I', 'UbaF14I', 'UbaF9I', 'UbaPI', 'UcoMSI', 'UnbI', 'Van9116I', 'Van91I', 'VchE4II', 'Vdi96II', 'Vha464I', 'VneI', 'VpaK11AI', 'VpaK11BI', 'VspI', 'Vtu19109I', 'WviI', 'XagI', 'XapI', 'XbaI', 'Xca85IV', 'XceI', 'XcmI', 'XhoI', 'XhoII', 'XmaI', 'XmaIII', 'XmaJI', 'XmiI', 'XmnI', 'XspI', 'YkrI', 'ZraI', 'ZrmI', 'Zsp2I'])

In [19]:
import pandas as pd
from Bio.Restriction import AllEnzymes

# Initialize an empty list to store enzyme information
enzyme_data = []

# Iterate through each enzyme in AllEnzymes
for enzyme in AllEnzymes:
    enzyme_info = {
        "Name": enzyme.__name__,
        "Site": enzyme.site,
        "Size": enzyme.size,
        "Is_Palindromic": enzyme.is_palindromic(),
        "Is_Blunt": enzyme.is_blunt(),
        "Is_5Overhang": enzyme.is_5overhang(),
        "Is_3Overhang": enzyme.is_3overhang(),
        "Is_Defined": enzyme.is_defined(),
        "Is_Ambiguous": enzyme.is_ambiguous(),
        "Is_Unknown": enzyme.is_unknown(),
        "Is_Commercially_Available": enzyme.is_comm(),
        "Suppliers": enzyme.supplier_list()
    }
    enzyme_data.append(enzyme_info)

# Create a DataFrame from the enzyme data
enzymes_df = pd.DataFrame(enzyme_data)

# Display the DataFrame
enzymes_df

,Name,Site,Size,Is_Palindromic,Is_Blunt,Is_5Overhang,Is_3Overhang,Is_Defined,Is_Ambiguous,Is_Unknown,Is_Commercially_Available,Suppliers
0,Bso31I,GGTCTC,6,False,False,True,False,False,True,False,True,"[SibEnzyme Ltd., Vivantis Technologies]"
1,Bst6I,CTCTTC,6,False,False,True,False,False,True,False,True,"[SibEnzyme Ltd., Vivantis Technologies]"
2,FauI,CCCGC,5,False,False,True,False,False,True,False,True,"[SibEnzyme Ltd., New England Biolabs]"
3,BveI,ACCTGC,6,False,False,True,False,False,True,False,True,[Life Technologies]
4,LweI,GCATC,5,False,False,True,False,False,True,False,True,[Life Technologies]
...,...,...,...,...,...,...,...,...,...,...,...,...
960,Rsp531II,CACACG,6,False,False,False,False,False,False,True,False,[]
961,HaeI,WGGCCW,6,True,True,False,False,True,False,False,False,[]
962,MspI7II,ACGRAG,6,False,False,False,False,False,False,True,False,[]
963,HinfI,GANTC,5,True,False,True,False,False,True,False,True,"[Life Technologies, Minotech Biotechnology, Si..."
964,VspI,ATTAAT,6,True,False,True,False,True,False,False,True,"[Life Technologies, SibEnzyme Ltd., Promega Co..."

In [22]:
dir(enzyme)

['__abstractmethods__',
 '__add__',
 '__base__',
 '__bases__',
 '__basicsize__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dictoffset__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__flags__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__instancecheck__',
 '__itemsize__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mro__',
 '__name__',
 '__ne__',
 '__new__',
 '__prepare__',
 '__qualname__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rshift__',
 '__rtruediv__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasscheck__',
 '__subclasses__',
 '__subclasshook__',
 '__text_signature__',
 '__truediv__',
 '__weakrefoffset__',
 '_drop',
 '_mod1',
 '_mod2',
 '_modify',
 '_rev_modify',
 '_search',
 'all_suppliers',
 'buffers',
 'catalyse',
 'catalyze',
 'charac',
 'characteristic',
 'compatible_end',
 'compsite',
 'cut_once',
 'cut_twice',
 'dna',
 'elucidate',
 'equischizomers',
 'freq',
 'frequency',
 'fst3',
 'fst5',
 'inact_temp',
 'is_3overhang',
 'is_5overhang',
 'is_ambiguous',
 'is_blunt',
 'is_comm',
 'is_defined',
 'is_equischizomer',
 'is_isoschizomer',
 'is_methylable',
 'is_neoschizomer',
 'is_palindromic',
 'is_unknown',
 'isoschizomers',
 'mro',
 'neoschizomers',
 'opt_temp',
 'overhang',
 'ovhg',
 'ovhgseq',
 'results',
 'scd3',
 'scd5',
 'search',
 'site',
 'size',
 'substrat',
 'suppl',
 'supplier_list',
 'suppliers']

In [11]:
from Bio.Restriction.Restriction_Dictionary import rest_dict
import numpy as np
import re
from Bio.Seq import Seq
import pandas as pd

In [13]:
df = pd.DataFrame(rest_dict).T
df

,charac,compsite,dna,freq,fst3,fst5,inact_temp,opt_temp,ovhg,ovhgseq,results,scd3,scd5,site,size,substrat,suppl
AanI,"(3, -3, None, None, TTATAA)",(?=(?P<AanI>TTATAA)),None,4096,-3,3,65,37,0,,None,None,None,TTATAA,6,DNA,"(B,)"
AarI,"(11, 8, None, None, CACCTGC)",(?=(?P<AarI>CACCTGC))|(?=(?P<AarI_as>GCAGGTG)),None,16384,8,11,65,37,-4,NNNN,None,None,None,CACCTGC,7,DNA,"(B,)"
AasI,"(7, -7, None, None, GACNNNNNNGTC)",(?=(?P<AasI>GAC......GTC)),None,4096,-7,7,65,37,2,NN,None,None,None,GACNNNNNNGTC,12,DNA,"(B,)"
AatII,"(5, -5, None, None, GACGTC)",(?=(?P<AatII>GACGTC)),None,4096,-5,5,65,37,4,ACGT,None,None,None,GACGTC,6,DNA,"(B, I, K, M, N, V)"
Aba6411II,"(None, None, None, None, CRRTAAG)",(?=(?P<Aba6411II>C[AG][AG]TAAG))|(?=(?P<Aba641...,None,4096,None,None,65,37,None,None,None,None,None,CRRTAAG,7,DNA,()
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XspI,"(1, -1, None, None, CTAG)",(?=(?P<XspI>CTAG)),None,256,-1,1,65,37,-2,TA,None,None,None,CTAG,4,DNA,"(K,)"
YkrI,"(11, 9, None, None, C)",(?=(?P<YkrI>C))|(?=(?P<YkrI_as>G)),None,4,9,11,65,37,1,N,None,None,None,C,1,DNA,()
ZraI,"(3, -3, None, None, GACGTC)",(?=(?P<ZraI>GACGTC)),None,4096,-3,3,65,37,0,,None,None,None,GACGTC,6,DNA,"(I, N, V)"
ZrmI,"(3, -3, None, None, AGTACT)",(?=(?P<ZrmI>AGTACT)),None,4096,-3,3,65,37,0,,None,None,None,AGTACT,6,DNA,"(I,)"
Zsp2I,"(5, -5, None, None, ATGCAT)",(?=(?P<Zsp2I>ATGCAT)),None,4096,-5,5,65,37,4,TGCA,None,None,None,ATGCAT,6,DNA,"(I, V)"

In [8]:
Bio.Restriction.AllEnzymes

RestrictionBatch(['AanI', 'AarI', 'AasI', 'AatII', 'Aba6411II', 'AbaB8342IV', 'AbaCIII', 'AbaSI', 'AbaUMB2I', 'AbsI', 'Acc16I', 'Acc36I', 'Acc65I', 'Acc65V', 'AccB1I', 'AccB7I', 'AccBSI', 'AccI', 'AccII', 'AccIII', 'AceIII', 'AchA6III', 'AciI', 'AclI', 'AclWI', 'Aco12261II', 'AcoI', 'AcoY31II', 'AcsI', 'AcuI', 'AcvI', 'AcyI', 'AdeI', 'Adh6U21I', 'AfaI', 'AfeI', 'AfiI', 'AflII', 'AflIII', 'AgeI', 'AgsI', 'AhaIII', 'AhdI', 'AhlI', 'AhyRBAHI', 'AhyYL17I', 'AjiI', 'AjnI', 'AjuI', 'AleI', 'AlfI', 'AloI', 'AluBI', 'AluI', 'Alw21I', 'Alw26I', 'Alw44I', 'AlwFI', 'AlwI', 'AlwNI', 'Ama87I', 'AmaCSI', 'Aod1I', 'Aor13HI', 'Aor51HI', 'AoxI', 'ApaBI', 'ApaI', 'ApaLI', 'ApeKI', 'ApoI', 'ApyPI', 'AquII', 'AquIII', 'AquIV', 'ArsI', 'AscI', 'AseI', 'Asi256I', 'AsiGI', 'AsiSI', 'Asp103I', 'Asp114pII', 'Asp700I', 'Asp718I', 'AspA2I', 'AspBHI', 'AspDUT2V', 'AspJHL3II', 'AspLEI', 'AspNIH4III', 'AspS9I', 'AspSLV7III', 'Asu14238IV', 'AsuC2I', 'AsuHPI', 'AsuI', 'AsuII', 'AsuNHI', 'AteTI', 'AvaI', 'AvaII', 'AvaIII', 'AvrII', 'Awo1030IV', 'AxyI', 'BaeGI', 'BaeI', 'Bag18758I', 'BalI', 'BamHI', 'BanI', 'BanII', 'BanLI', 'BarI', 'Bau1417V', 'BauI', 'Bbr52II', 'Bbr57III', 'Bbr7017II', 'Bbr7017III', 'BbrPI', 'BbsI', 'BbuB31I', 'BbuB31II', 'Bbv12I', 'BbvCI', 'BbvI', 'BbvII', 'BccI', 'Bce3081I', 'Bce83I', 'BceAI', 'BceSIV', 'BcefI', 'BcgI', 'BciT130I', 'BciVI', 'BclI', 'BcnI', 'BcoDI', 'BcuI', 'BdaI', 'BetI', 'BfaI', 'BfaSII', 'BfiI', 'BfmI', 'BfoI', 'BfrI', 'BfuAI', 'BfuI', 'Bga514I', 'BglI', 'BglII', 'BinI', 'BisI', 'BkrAM31DI', 'Ble402II', 'BlnI', 'BloAII', 'BlpI', 'BlsI', 'BmcAI', 'Bme1390I', 'Bme18I', 'BmeDI', 'BmeRI', 'BmeT110I', 'BmgBI', 'BmgI', 'BmgT120I', 'BmiI', 'BmrFI', 'BmrI', 'BmsI', 'BmtI', 'BmuI', 'BoxI', 'BpiI', 'BplI', 'BpmI', 'Bpu10I', 'Bpu1102I', 'Bpu14I', 'BpuEI', 'BpuMI', 'Bsa29I', 'BsaAI', 'BsaBI', 'BsaHI', 'BsaI', 'BsaJI', 'BsaWI', 'BsaXI', 'BsbI', 'Bsc4I', 'BscAI', 'BscGI', 'Bse118I', 'Bse1I', 'Bse21I', 'Bse3DI', 'Bse8I', 'BseAI', 'BseBI', 'BseCI', 'BseDI', 'BseGI', 'BseJI', 'BseLI', 'BseMI', 'BseMII', 'BseNI', 'BsePI', 'BseRI', 'BseSI', 'BseX3I', 'BseXI', 'BseYI', 'BsgI', 'Bsh1236I', 'Bsh1285I', 'BshFI', 'BshNI', 'BshTI', 'BshVI', 'BsiEI', 'BsiHKAI', 'BsiHKCI', 'BsiI', 'BsiSI', 'BsiWI', 'BsiYI', 'BslFI', 'BslI', 'BsmAI', 'BsmBI', 'BsmFI', 'BsmI', 'BsnI', 'Bso31I', 'BsoBI', 'Bsp119I', 'Bsp120I', 'Bsp1286I', 'Bsp13I', 'Bsp1407I', 'Bsp143I', 'Bsp1720I', 'Bsp19I', 'Bsp24I', 'Bsp3004IV', 'Bsp460III', 'Bsp68I', 'BspACI', 'BspANI', 'BspCNI', 'BspD6I', 'BspDI', 'BspEI', 'BspFNI', 'BspGI', 'BspHI', 'BspLI', 'BspLU11I', 'BspMAI', 'BspMI', 'BspMII', 'BspNCI', 'BspOI', 'BspPI', 'BspQI', 'BspT104I', 'BspT107I', 'BspTI', 'BspTNI', 'BsrBI', 'BsrDI', 'BsrFI', 'BsrGI', 'BsrI', 'BssAI', 'BssECI', 'BssHII', 'BssMI', 'BssNAI', 'BssNI', 'BssSI', 'BssT1I', 'Bst1107I', 'Bst2BI', 'Bst2UI', 'Bst4CI', 'Bst6I', 'BstACI', 'BstAFI', 'BstAPI', 'BstAUI', 'BstBAI', 'BstBI', 'BstC8I', 'BstDEI', 'BstDSI', 'BstEII', 'BstENI', 'BstF5I', 'BstFNI', 'BstH2I', 'BstHHI', 'BstKTI', 'BstMAI', 'BstMBI', 'BstMCI', 'BstMWI', 'BstNI', 'BstNSI', 'BstPAI', 'BstPI', 'BstSCI', 'BstSFI', 'BstSLI', 'BstSNI', 'BstUI', 'BstV1I', 'BstV2I', 'BstX2I', 'BstXI', 'BstYI', 'BstZ17I', 'BstZI', 'Bsu15I', 'Bsu36I', 'BsuI', 'BsuRI', 'BsuTUI', 'BtgI', 'BtgZI', 'BthCI', 'BtrI', 'BtsCI', 'BtsI', 'BtsIMutI', 'BtuMI', 'Bve1B23I', 'BveI', 'Cac8I', 'CaiI', 'Cal14237I', 'CalB3II', 'Cau10061II', 'CauII', 'Cba13II', 'Cba16038I', 'Cbo67071IV', 'Cch467III', 'CchII', 'CchIII', 'CciI', 'CciNI', 'Cco14983V', 'Cco14983VI', 'CcrNAIII', 'Cdi11397I', 'CdiI', 'CdpI', 'Cdu23823II', 'CfoI', 'Cfr10I', 'Cfr13I', 'Cfr42I', 'Cfr9I', 'CfrI', 'CfrMH13II', 'CfrMH16VI', 'Cfupf3II', 'Cgl13032I', 'Cgl13032II', 'ChaI', 'Cje265V', 'Cje54107III', 'CjeFIII', 'CjeFV', 'CjeI', 'CjeNII', 'CjeNIII', 'CjeNV', 'CjeP659IV', 'CjePI', 'CjuI', 'CjuII', 'Cla11845III', 'ClaI', 'Cly7489II', 'Cma23826I', 'CpoI', 'CseI', 'CsiI', 'Csp2014I', 'Csp6I', 'CspAI', 'CspCI', 'CspI', 'CstMI', 'CviAII', 'CviJI', 'CviKI_1', 'CviQI', 'CviRI', 'Dde51507I', 'DdeI', 'DinI', 'DpnI', 'DpnII', 'DraI', 'DraII', 'DraIII', 'DraRI', 'DrdI', 'DrdII', 'DrdIV', 'DriI', 'DsaI', 'DseDI', 'DvuIII', 'EaeI', 'EagI', 'Eam1104I', 'Eam1105I', 'EarI', 'EciI', 'Ecl136II', 'Ecl234I', 'Ecl35734I', 'EclXI', 'Eco105I', 'Eco130I', 'Eco147I', 'Eco24I', 'Eco31I', 'Eco32I', 'Eco43896II', 'Eco4465II', 'Eco47I', 'Eco47III', 'Eco52I', 'Eco53kI', 'Eco57I', 'Eco57MI', 'Eco72I', 'Eco81I', 'Eco88I', 'Eco91I', 'EcoBLMcrX', 'EcoE1140I', 'EcoHI', 'EcoHSI', 'EcoICRI', 'EcoMVII', 'EcoNI', 'EcoNIH6II', 'EcoO109I', 'EcoO65I', 'EcoRI', 'EcoRII', 'EcoRV', 'EcoT14I', 'EcoT22I', 'EcoT38I', 'EgeI', 'EheI', 'Eli8509II', 'ErhI', 'EsaBC3I', 'EsaSSI', 'Esp3007I', 'Esp3I', 'EspI', 'FaeI', 'FaiI', 'FalI', 'FaqI', 'FatI', 'FauI', 'FauNDI', 'FbaI', 'FblI', 'Fco1691IV', 'FinI', 'FmuI', 'Fnu4HI', 'FnuDII', 'FokI', 'FriOI', 'FseI', 'Fsp4HI', 'FspAI', 'FspBI', 'FspEI', 'FspI', 'FspPK15I', 'FtnUV', 'GauT27I', 'Gba708II', 'GdiII', 'GlaI', 'GluI', 'GsaI', 'GsuI', 'HaeI', 'HaeII', 'HaeIII', 'HapII', 'HauII', 'HbaII', 'HdeNY26I', 'HdeZA17I', 'HgaI', 'HgiAI', 'HgiCI', 'HgiEII', 'HgiJII', 'HhaI', 'Hin1I', 'Hin1II', 'Hin4I', 'Hin4II', 'Hin6I', 'HinP1I', 'HincII', 'HindII', 'HindIII', 'HinfI', 'HpaI', 'HpaII', 'HphI', 'Hpy166II', 'Hpy178III', 'Hpy188I', 'Hpy188III', 'Hpy300XI', 'Hpy8I', 'Hpy99I', 'Hpy99XIII', 'Hpy99XIV', 'Hpy99XIV_mut1', 'Hpy99XXII', 'HpyAV', 'HpyAXIV', 'HpyAXVIII', 'HpyAXVI_mut1', 'HpyAXVI_mut2', 'HpyCH4III', 'HpyCH4IV', 'HpyCH4V', 'HpyF10VI', 'HpyF3I', 'HpySE526I', 'HpyUM032XIII', 'HpyUM032XIII_mut1', 'HpyUM032XIV', 'HpyUM037X', 'Hsp92I', 'Hsp92II', 'HspAI', 'HspMHR1II', 'Jma19592I', 'Jma19592II', 'Jsp2502II', 'KasI', 'KflI', 'Kor51II', 'Kpn156V', 'Kpn2I', 'Kpn327I', 'KpnI', 'KpnNH25III', 'KpnNIH30III', 'KpnNIH50I', 'KroI', 'Ksp22I', 'Ksp632I', 'KspAI', 'KspI', 'Kzo9I', 'Lba2029III', 'Lde4408II', 'LguI', 'LlaG50I', 'LmnI', 'Lmo370I', 'Lmo911II', 'Lpl1004II', 'LpnI', 'LpnPI', 'Lra68I', 'LsaDS4I', 'Lsp1109I', 'Lsp48III', 'Lsp6406VI', 'LweI', 'MabI', 'MaeI', 'MaeII', 'MaeIII', 'MalI', 'MaqI', 'MauBI', 'Mba11I', 'MbiI', 'MboI', 'MboII', 'McaTI', 'Mcr10I', 'McrI', 'MfeI', 'MflI', 'MhlI', 'MjaIV', 'MkaDII', 'MlsI', 'Mlu211III', 'MluCI', 'MluI', 'MluNI', 'Mly113I', 'MlyI', 'MmeI', 'MnlI', 'Mox20I', 'Mph1103I', 'MreI', 'MroI', 'MroNI', 'MroXI', 'MscI', 'MseI', 'MslI', 'Msp20I', 'MspA1I', 'MspCI', 'MspGI', 'MspI', 'MspI7II', 'MspI7IV', 'MspJI', 'MspR9I', 'MspSC27II', 'MssI', 'MstI', 'MteI', 'MtuHN878II', 'MunI', 'Mva1269I', 'MvaI', 'MvnI', 'MwoI', 'NaeI', 'Nal45188II', 'NarI', 'Nbr128II', 'NciI', 'NcoI', 'NdeI', 'NdeII', 'NgoAVII', 'NgoAVIII', 'NgoMIV', 'NhaXI', 'NheI', 'NhoI', 'NlaCI', 'NlaIII', 'NlaIV', 'Nli3877I', 'NmeA6CIII', 'NmeAIII', 'NmeDI', 'NmuCI', 'NotI', 'NpeUS61II', 'NruI', 'NsbI', 'NsiI', 'NspBII', 'NspI', 'NspV', 'ObaBS10I', 'OgrI', 'OliI', 'OspHL35III', 'PabI', 'Pac19842II', 'PacI', 'PacIII', 'PaeI', 'PaeR7I', 'PagI', 'Pal408I', 'PalAI', 'PasI', 'PauI', 'Pba2294I', 'PcaII', 'PceI', 'PciI', 'PciSI', 'Pcr308II', 'PcsI', 'PctI', 'Pdi8503III', 'PdiI', 'PdmI', 'Pdu1735I', 'PenI', 'PfeI', 'Pfl1108I', 'Pfl23II', 'Pfl8569I', 'PflFI', 'PflMI', 'PflPt14I', 'PfoI', 'PfrJS12IV', 'PfrJS12V', 'PfrJS15III', 'Pin17FIII', 'PinAI', 'PinP23II', 'PinP59III', 'PkrI', 'PlaDI', 'Ple19I', 'PleI', 'PliMI', 'PluTI', 'PmaCI', 'PmeI', 'PmlI', 'PpiI', 'PpiP13II', 'PpsI', 'Ppu10I', 'Ppu21I', 'PpuMI', 'PscI', 'Pse18267I', 'PshAI', 'PshBI', 'PsiI', 'Psp0357II', 'Psp03I', 'Psp124BI', 'Psp1406I', 'Psp5II', 'Psp6I', 'PspCI', 'PspEI', 'PspFI', 'PspGI', 'PspLI', 'PspN4I', 'PspOMI', 'PspOMII', 'PspPI', 'PspPPI', 'PspPRI', 'PspXI', 'PsrI', 'PssI', 'Pst14472I', 'Pst145I', 'Pst273I', 'PstI', 'PstNI', 'PsuGI', 'PsuI', 'PsyI', 'PteI', 'PvuI', 'PvuII', 'Rba2021I', 'RceI', 'RdeGBI', 'RdeGBII', 'RdeGBIII', 'RflFIII', 'RgaI', 'RigI', 'RlaI', 'RlaII', 'RleAI', 'Rmu369III', 'RpaB5I', 'RpaBI', 'RpaI', 'RpaTI', 'RruI', 'RsaI', 'RsaNI', 'RseI', 'Rsp008IV', 'Rsp008V', 'Rsp531II', 'RspPBTS2III', 'Rsr2I', 'RsrII', 'Rtr1953I', 'SacI', 'SacII', 'Saf8902III', 'Sag901I', 'SalI', 'SanDI', 'SapI', 'SaqAI', 'SatI', 'Sau3AI', 'Sau96I', 'SauI', 'Sba460II', 'SbfI', 'Sbo46I', 'ScaI', 'SchI', 'SciI', 'ScoDS2II', 'ScrFI', 'SdaI', 'SdeAI', 'SdeOSI', 'SduI', 'SecI', 'SelI', 'Sen17963III', 'SenA1673III', 'SenSARA26III', 'SenTFIV', 'SetI', 'SexAI', 'SfaAI', 'SfaNI', 'SfcI', 'SfeI', 'SfiI', 'SfoI', 'Sfr274I', 'Sfr303I', 'SfuI', 'SgeI', 'SgfI', 'SgrAI', 'SgrBI', 'SgrDI', 'SgrTI', 'SgsI', 'SimI', 'SinI', 'SlaI', 'SmaI', 'SmaUMH5I', 'SmaUMH8I', 'SmiI', 'SmiMI', 'SmlI', 'SmoI', 'SnaBI', 'SnaI', 'Sno506I', 'SpeI', 'SphI', 'SplI', 'SpnRII', 'SpoDI', 'SrfI', 'Sse232I', 'Sse8387I', 'Sse8647I', 'Sse9I', 'SseBI', 'SsiI', 'Ssp6803IV', 'Ssp714II', 'SspD5I', 'SspDI', 'SspI', 'SspMI', 'SstE37I', 'SstI', 'Sth132I', 'Sth20745III', 'Sth302II', 'SthSt3II', 'StsI', 'StuI', 'StyD4I', 'StyI', 'SurP32aII', 'SwaI', 'TaaI', 'TaiI', 'TaqI', 'TaqII', 'TaqIII', 'TasI', 'TatI', 'TauI', 'TfiI', 'TpyTP2I', 'Tru1I', 'Tru9I', 'TscAI', 'TseFI', 'TseI', 'TsoI', 'Tsp45I', 'Tsp4CI', 'TspARh3I', 'TspDTI', 'TspEI', 'TspGWI', 'TspMI', 'TspRI', 'TssI', 'TstI', 'TsuI', 'Tth111I', 'Tth111II', 'UbaF11I', 'UbaF12I', 'UbaF13I', 'UbaF14I', 'UbaF9I', 'UbaPI', 'UcoMSI', 'UnbI', 'Van9116I', 'Van91I', 'VchE4II', 'Vdi96II', 'Vha464I', 'VneI', 'VpaK11AI', 'VpaK11BI', 'VspI', 'Vtu19109I', 'WviI', 'XagI', 'XapI', 'XbaI', 'Xca85IV', 'XceI', 'XcmI', 'XhoI', 'XhoII', 'XmaI', 'XmaIII', 'XmaJI', 'XmiI', 'XmnI', 'XspI', 'YkrI', 'ZraI', 'ZrmI', 'Zsp2I'])

In [4]:
help(Bio.Restriction)

Help on package Bio.Restriction in Bio:

NAME
    Bio.Restriction - Restriction Digest Enzymes.

DESCRIPTION
    Examples
    --------
        >>> from Bio.Seq import Seq
        >>> from Bio.Restriction import *
        >>> pBs_mcs = 'GGTACCGGGCCCCCCCTCGAGGTCGACGGTATCGATAAGCTTGATATCGAATTCCTG'
        >>> pBs_mcs += 'CAGCCCGGGGGATCCACTAGTTCTAGAGCGGCCGCCACCGCGGTGGAGCTC'
        >>> seq = Seq(pBs_mcs)  # Multiple-cloning site of pBluescript SK(-)
        >>> a = Analysis(AllEnzymes, seq)
        >>> a.print_that()              # no argument -> print all the results
        AbaSI      :  10, 12, 13, 16, 17, 18, 19, 20, 22, 23, 24, 25, 25, 26, 27...
        BmeDI      :  2, 7, 8, 8, 9, 9, 13, 14, 15, 16, 17, 18, 19, 19, 21, 21...
        YkrI       :  10, 12, 13, 16, 16, 17, 19, 20, 21, 22, 23, 24, 25, 25, 26...

        BmeDI      :  1, 2, 7, 8, 8, 9, 9, 13, 14, 15, 16, 17, 18, 19...
        AccII      :  98.
        AciI       :  86, 90, 96, 98...

        Enzymes which do not cut the sequence.

        AspLEI    BstHHI    CfoI      CviAII    FaeI      FaiI      FatI      GlaI
        HhaI      Hin1II    Hin6I     HinP1I    HpyCH4IV  HpySE526I Hsp92II   HspAI
        MaeII     MseI      NlaIII    SaqAI     TaiI      Tru1I     Tru9I...
        <BLANKLINE>
        >>> b = a.blunt()  # Analysis with blunt enzmyes
        >>> a.print_that(b)  # Print results for blunt cutters
        AccII      :  98.
        AfaI       :  4.
        AluBI      :  40, 106.
        AluI       :  40, 106.
        Bsh1236I   :  98.
        BshFI      :  10, 89.
        BsnI       :  10, 89.
        BspANI     :  10, 89...

        Enzymes which do not cut the sequence.

        FaiI      GlaI      CdiI      MlyI      SchI      SspD5I    AanI...
        <BLANKLINE>

PACKAGE CONTENTS
    PrintFormat
    Restriction
    Restriction_Dictionary

DATA
    AllEnzymes = RestrictionBatch(['AanI', 'AarI', 'AasI', 'AatII...'XmnI'...
    CommOnly = RestrictionBatch(['AanI', 'AarI', 'AasI', 'AatII...'XmiI', ...
    NonComm = RestrictionBatch(['Aba6411II', 'AbaB8342IV', 'Ab...', 'WviI'...

FILE
    /home/wenzhao/miniconda3/envs/PyRosetta.notebooks/lib/python3.7/site-packages/Bio/Restriction/__init__.py

In [2]:
from Bio.Seq import Seq

# Example DNA sequence
dna_seq = "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"

# Create a Seq object
coding_dna = Seq(dna_seq)

# Translate to protein
protein_seq = coding_dna.translate()

print(f"DNA sequence: {dna_seq}")
print(f"Protein sequence: {protein_seq}")

DNA sequence: ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG
Protein sequence: MAIVMGR*KGAR*